- name: Create jenkins jobs
  hosts: localhosts
  tasks:
    - name: Create a jenkins jobs using  basic authentication
      community.general.jenkins_jobs:
        config: "{{ lookup('file', 'templates/test.xml') }}"
        name: test
        password: admin
        url: https://172.31.12.47:8080
        user: admin