- name: Create a jenkins jobs using  basic authentication
  community.general.jenkins_job:
      config: "{{ lookup('file', 'templates/single-pipeline.xml') }}"
      name: test
      password: admin123
      url: https://localhost:8080
      user: admin


