- name: Create jenkins jobs
  hosts: all
  tasks:
  - name: Create a jenkins jobs using  basic authentication
    community.general.jenkins_jobs:
      config: "{{ lookup('file', 'templates/single-pipeline.xml') }}"
      name: test
      password: admin
      url: https://172.31.2.68:8080
      user: admin


