- name: Create a folder
  community.general.jenkins_job:
      config: "{{ lookup('file', 'templates/folder.xml') }}"
      name: "{{item}}"
      password: 11aee1369b4389af204a8e88d2348ec7ca
      url: http://172.31.10.150:8080
      user: sarabjeet310
  loop:
   - CI-Pipeline

- name: Include task list in play
  ansible.builtin.include_tasks: s-pipeline.yml
  vars:
    COMPONENT: "{{item}}"
  loop:
    - frontend
    - catalogue
    - cart
    - user
    - shipping
    - payment

