- name: Create a template
  ansible.builtin.template:
    src: s-pipeline.xml
    dest: /tmp/s-pipeline.xml


- name: Create a jenkins jobs using  basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-pipeline.xml') }}"
    name: "CI-Pipeline/{{item}}"
    password: 11aee1369b4389af204a8e88d2348ec7ca
    #password: admin123
    url: http://172.31.10.150:8080
    user: sarabjeet310
    #user: admin


