- name: Create a template
  ansible.builtin.template:
    remote_src: true
    src: s-pipeline.xml
    dest: /template/s-pipeline.xml

- name: Create a jenkins jobs using  basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', '/template/s-pipeline.xml') }}"
    name: "CI-Pipeline/{{item}}"
    password: 11aee1369b4389af204a8e88d2348ec7ca
    #password: admin123
    url: http://172.31.2.68:8080
    user: sarabjeet310
    #user: admin


